# Generated by Django 4.2.4 on 2023-08-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
        ('administracion', '0002_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ManyToManyField(to='profesor.profesor'),
        ),
    ]
