# Generated by Django 4.2.4 on 2023-08-06 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=8)),
                ('turno', models.CharField(max_length=256)),
                ('disponibilidad', models.CharField(max_length=256)),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.posicion')),
            ],
        ),
    ]
